#include <iostream>
using namespace std;

int main() {
    cout << "-----------------------------\n";
    cout << "\tStudent ID Card\n";
    cout << "-----------------------------\n";
    cout << "Name:\t\tAli Raza\n";
    cout << "Roll No:\t12345\n";
    cout << "Department:\tComputer Science\n";
    cout << "Session:\t2024-2028\n";
    cout << "-----------------------------\n\n";


    cout << "******** MENU *********************\n";
    cout << "1.\tBiryani\t\tRs. 350\n";
    cout << "2.\tKarahi\t\tRs. 600\n";
    cout << "3.\tQorma\t\tRs. 500\n";
    cout << "4.\tDrinks\t\tRs. 100\n";
    cout << "***********************************\n\n";

    cout << "-------------------------------------------\n";
    cout << "\tCertificate of Achievement\n";
    cout << "-------------------------------------------\n";
    cout << "This is to certify that \"Ali Raza\"\n";
    cout << "has successfully completed the\n";
    cout << "course \"C++ Programming\" with A+ Grade.\n";
    cout << "-------------------------------------------\n\n";

    cout << "+---------------------+\n";
    cout << "| Roll No | Marks     |\n";
    cout << "+---------------------+\n";
    cout << "|  101    |   89      |\n";
    cout << "|  102    |   92      |\n";
    cout << "|  103    |   85      |\n";
    cout << "+---------------------+\n";

    return 0;
}
